/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.ImageIcon;
import reglas.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.SqlUsuarios;
import login.Hash;
import login.Registro;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    public static presentacion.Registro frmReg;
    public static Principal frmHome;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/LogoCt.png")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelClave = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldClave = new javax.swing.JPasswordField();
        fieldUsuario = new javax.swing.JTextField();
        botonIniciar = new javax.swing.JButton();
        labelCrearUsuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(420, 325));
        setPreferredSize(new java.awt.Dimension(420, 325));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClave.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelClave.setText("Contraseña:");
        getContentPane().add(labelClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelUsuario.setText("Usuario:");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        getContentPane().add(fieldClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 130, 30));

        fieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 30));

        botonIniciar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        botonIniciar.setText("Iniciar sesión");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        labelCrearUsuario.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        labelCrearUsuario.setForeground(new java.awt.Color(153, 0, 0));
        labelCrearUsuario.setText("Crear usuario");
        labelCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(labelCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginImagen.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:
        SqlUsuarios modSqul = new SqlUsuarios();
        Registro mod = new Registro();

        String contra = new String(fieldClave.getPassword());

        if (!fieldUsuario.getText().equals("") && !contra.equals("")) {

            String nuevaContra = Hash.sha2(contra);

            mod.setUsuario(fieldUsuario.getText());
            mod.setContraseña(nuevaContra);

            try {
                if (modSqul.login(mod)) {

                    this.dispose();
                    frmHome = new Principal(mod);
                    frmHome.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Datos incorrectos");

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void labelCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearUsuarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        frmReg = new presentacion.Registro();
        frmReg.setVisible(true);
    }//GEN-LAST:event_labelCrearUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JPasswordField fieldClave;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelCrearUsuario;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
